name: ci

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install dependencies
        run: poetry install --without dev

      - name: Check Formatting
        run: poetry run black --check .

      - name: Lint
        run: poetry run pyright

      - name: Test
        run: poetry run pytest

      - name: Test Docs
        run: |
          cd docs
          poetry run make doctest
          poetry run make html

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install dependencies
        run: poetry install --without dev

      - name: Build
        run: poetry build

      - name: Setup pypi upload
        run: poetry config pypi-token.pypi $PYPI_API_TOKEN
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish
        run: poetry publish
